# -*- coding: utf-8 -*-
"""aishitachhabda_b2_24_aimllab1b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mquQlD_1ypClqAybwsZe6jVGoci5rgtV
"""

import numpy as np
import pandas as pd
from sklearn.impute import simpleImputer

df=pd.read_csv('/content/titanic.csv')

df.describe()

df.head(10)

df.shape

df.shape[0]

df.shape[1]

df.columns[3:5]

df.columns

df.info()

df.head(25)

df.describe(include=[int])

df.describe(exclude=[int])

df.isna()

df.head(25)

df.isna().sum()

df.isnull()

df.describe()

print("Shape(rows,columns):",df.shape)
print("\nColunms:", list(df.columns))
print("\nData types:\n", df.dtypes)

df["Age"].mean()

df["Age"].mean().round(2)

df["Age"].isna().sum()

df["Survived"].value_counts()

df["Survived"].value_counts(normalize=True)*100

df1=df.copy()

df1.head()

df1=df.copy()
df.head(10)

df.info()

df.isnull()

df.isnull()

df1["Age"].isna().sum()
print("Age",df1.Age)

df1["Age"] = df1["Age"].fillna(df1["Age"].mean())
print("Missing Age before:", df1["Age"].isna().sum())

df1.head(50)

df1["Age"].head()

from sklearn.impute import SimpleImputer

num_imputer = SimpleImputer(strategy= 'median')
df1["Age"]=num_imputer.fit_transform(df1[["Age"]])
num_imputer.fit(df1[['Age']])
print(num_imputer.statistics_)

df1["Age"].head(25)

df.head(25)

df1["Embarked"].isna()

df1["Embarked"].isna().sum()

from sklearn.impute import SimpleImputer

num_imputer = SimpleImputer(strategy='most_frequent')
df1[["Embarked"]] = num_imputer.fit_transform(df1[["Embarked"]])

print(num_imputer.statistics_)

df1=df.copy()

