# -*- coding: utf-8 -*-
"""aishita_aiml_lab3b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mQhRcLzCwmoNmdJC6Mvm5SaiBiX1xlVP
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
sns.set(style='whitegrid')

x = [1, 2, 3, 4, 5]
y = [10, 15, 13, 18, 16]

plt.plot(x, y)
plt.title('Line Plot')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.grid(True)
plt.show()

# Scatter Plot
x = np.random.rand(50)
y = np.random.rand(50)
plt.scatter(x, y, color='r')
plt.title('Scatter Plot')
plt.show()

# Bar Plot
x = ['A', 'B', 'C']
y = [3, 7, 5]
plt.bar(x, y)
plt.title('Bar Chart')
plt.show()

# Histogram
data = np.random.randn(1000)
plt.hist(data, bins=30, color='purple')
plt.title('Histogram')
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.show()

x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)

plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.plot(x, y1)
plt.title('Sine')

plt.subplot(1, 2, 2)
plt.plot(x, y2)
plt.title('Cosine')

plt.tight_layout()
plt.show()

# Create 1 row, 2 columns of subplots
fig, axs = plt.subplots(2, 2, figsize=(10, 4))

# Plot on each axis
axs[0,0].plot([1, 2, 3], [1, 4, 9])
axs[0,0].set_title("First Plot")

axs[1,0].plot([1, 2, 3], [1, 2, 3])
axs[1,0].set_title("Second Plot")

plt.tight_layout()
plt.show()

iris = sns.load_dataset('iris')
iris.head()

sns.histplot(iris['sepal_length'], kde=True, bins=20, color='green')
plt.title('Histogram of Sepal Length')
plt.show()

sns.scatterplot(data=iris, x='sepal_length', y='sepal_width', hue='species')
plt.title('Sepal Length vs Width')
plt.show()

sns.boxplot(data=iris, x='species', y='petal_length')
plt.title('Petal Length by Species')
plt.show()

sns.pairplot(iris, hue='species')
plt.suptitle('Pairplot of Iris Features', y=1.02)
plt.show()