# -*- coding: utf-8 -*-
"""aishita_24_aiml4bfs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13R8aF8IfXRCtTkZGGASfchH-dvfDSf2M
"""

from collections import deque

graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': [],
    'F': []
}

start = 'A'# start is the string:
goal = 'F'

print (graph)

import matplotlib.pyplot as plt

# Your tree/graph (adjacency list)
graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': [],
    'F': []
}

# 1) Give each node a position (x, y)
pos = {
    'A': (0, 2),
    'B': (-1, 1),
    'C': ( 1, 1),
    'D': (-1.5, 0),
    'E': (-0.5, 0),
    'F': ( 1.0, 0),
}

plt.figure(figsize=(7,4))

# 2) Draw edges (lines)
for u in graph:
    x1, y1 = pos[u]
    for v in graph[u]:
        x2, y2 = pos[v]
        plt.plot([x1, x2], [y1, y2])  # simple line

# 3) Draw nodes (points) + labels
for n, (x, y) in pos.items():
    plt.scatter(x, y, s=600)
    plt.text(x, y, n, ha='center', va='center', fontsize=14)

plt.title("Tree Visualization using Matplotlib")
plt.axis('off')
plt.show()

print("start =", start, "goal =", goal)

queue = deque([start])
type (queue)

q=deque()

print(q)

step = 0
type(step)

from collections import deque

# Example graph (you can modify this)
graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

# -------------------------------
# 1) Initialization
# -------------------------------
start = 'A'
goal = 'F'

queue = deque([start])
visited = set([start])
parent = {start: None}   # NEW: parent map for path reconstruction
step = 0

print("Initial queue:", list(queue))
print("Initial visited:", visited)
print("Initial parent :", parent)

# -------------------------------
# 2) BFS Loop
# -------------------------------
while queue:

    # Increment step counter
    step += 1

    # Remove node from queue (FIFO)
    node = queue.popleft()

    print("\nSTEP", step)
    print("Popped node:", node)
    print("Queue after pop:", list(queue))

    # Goal check
    if node == goal:
        print("Goal found! Stop BFS.")
        break

    # Explore neighbors
    for neighbor in graph[node]:
        print("Checking neighbor:", neighbor)

        # Check if not visited
        if neighbor not in visited:

            # Mark visited
            visited.add(neighbor)

            # Store parent
            parent[neighbor] = node

            # Add to queue
            queue.append(neighbor)

            # Print updates
            print("  Added to visited:", neighbor)
            print(f"  parent[{neighbor}] = {node}")
            print("  Added to queue:", neighbor)

    print("Queue now:", list(queue))
    print("Visited now:", visited)


print("\nBFS ended.")
print("Final visited:", visited)
print("Final parent :", parent)


path = []
current = goal

while current is not None:
    path.append(current)
    current = parent.get(current)

path.reverse()
print("Path from start to goal:", path)

print("Initial State")
print("queue  :", list(queue))
print("visited:", visited)
print("step   :", step)
print("parent  :", parent)

def reconstruct_path(parent, start, goal):

    if goal not in parent:
        return None

    path = []

    current = goal# Start from the goal and walk backward


    while current is not None:
        path.append(current)
        current = parent[current]

    path.reverse()
    return path

path = reconstruct_path(parent, start, goal)

print("\nShortest path from", start, "to", goal, ":")
print(path)