# -*- coding: utf-8 -*-
"""aishita_24_b2_aimllab4dfs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GiqGinMdHaQkJTbH8F8wlcily_merD6W
"""

import heapq
import pandas as pd
OPEN = []
heapq.heappush(OPEN, (5,2, 'X'))
heapq.heappush(OPEN, (3,1, 'Y'))
heapq.heappush(OPEN, (4,1, 'Z'))


pd.DataFrame(sorted(OPEN), columns=["f(n)", "g(n)","node"])

graph = {
    'A': [('B',11) , ('C',14), ('D',7)],
    'B': [('A',11) , ('E',15)],
    'C': [('A',14) , ('E',8), ('F',10)],
    'D': [('A',7) , ('F',25)],
    'E': [('B',15) , ('C',8), ('H',9)],
    'F': [('C',10) , ('D',25), ('G',20)],
    'H': [('E',9), ('G',15)],
    'G': [('F',20) , ('H',10)]
}

print(graph)


start = 'A'
goal = 'G'

print("Start:",start,"| Goal:", goal)
print("Neighbours of A:", graph ['A'])
print("Neighbours of G:", graph ['G'])

def reconstruct_path(parent, start, goal):
  if goal not in parent:
      return None
  path = []
  current= goal

  while current is not None:
   current.append(current)
   current= parent[current]

  path.reverse()

  return path

print(reconstruct_path(parent='A',start='B',goal='G'))

def astar(graph, start, goal, h):
  OPEN = []

  visited = set()
  parent = {start: None}
  g_cost = {start: 0}
  heapq.heappush(OPEN, (h[start], 0, start))

  while OPEN:
    f_current, g_current, current = heapq.heappop(OPEN)

    if current in visited:
       continue
    print("Selected:", current, "| g =", g_current, "| f =", f_current)

    if current == goal:
      break
    visited.add(current)

    for neighbor, cost in graph[current]:
      if neighbor in visited:
        continue

      new_g = g_cost[current] + cost
      if (neighbor not in g_cost) or (new_g < g_cost[neighbor]):

        g_cost[neighbor] = new_g
        parent[neighbor] = current
        new_f = new_g + h[neighbor]
        heapq.heappush(OPEN, (new_f, new_g, neighbor))
  path = reconstruct_path(parent, start, goal)

  return path, g_cost.get(goal, None), parent, g_cost

# CELL 6
# Run A* and display final outputs

path, total_cost, parent, g_cost = astar(graph, start, goal, h)

print("\n--- FINAL OUTPUT ---")
print("Path (start -> goal):", path)
print("Total cost of path:", total_cost)

print("\nParent map (used for reconstruction):")
print(parent)

print("\ng_cost map (best known costs from start):")
print(g_cost)

